### PR TITLE
Delete Functionality Ready, Refactoring

### PR DESCRIPTION
**Pull request by HarshKhandeparkar**
Demo: https://harshkhandeparkar.github.io/image-sequencer-ui
Delete Functionality Ready
delete-function

I have also refactored some of the code
@harshithpabbati @rexagod please go through this properly. And let's merge this only after all of us review it. Thanks!

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
This contains the changes in #6

**Comment by jywarren** [comment]
This is looking really nice! Is it fully compatible with the existing main branch of `image-sequencer`? Also, have you thought ahead to UI tests? thanks!

**Comment by HarshKhandeparkar** [comment]
I am planning on adding UI tests in a future pr. And yes, it can be
packaged into a standalone webapp and can be added to the /examples.

**Comment by HarshKhandeparkar** [comment]
Hi all. I want to continue with the future plans and features so I am going to merge this pr without reviews. I believe the reviewers don't get time to review and that is totally understandable. Since I want to continue, I'll have to merge this pr. Thank you all!

@harshithpabbati @rexagod @jywarren

**Pull request merged**
